### ISSUE TITLE
Inverse impossible to define

### ISSUE THREAD

**Issue by VincentSe** [andrejbauer/dedekind-reals#14]
Hi Andrej,

I think that `upper_bound : {r : Q | upper r}` won't let you define the inverse of a real number, because of the sort `Type`.

Take a positive real number `x`, but very very small. Then a rational number `q > 1/x` will be gigantic, and the only way to compute it is to find a rational number `0 < r < x`. That suggests to use `lower_open x 0`, but you cannot because it is in sort `Prop`.

Anyway why did you use the sort `Type` for the bounds and the sort `Prop` everywhere else ? As we already discussed you want the Dedekind reals, not the Cauchy reals, so you probably want `Prop` everywhere.

**Comment by andrejbauer** [comment]
At first I tried to use `Type` and later I realized it should be `Prop`. I think the `upper_bound` is just a remnant of that, I forgot to fix it. We should just switch to `upper_bound : { r : Q & upper r }`. Will you make the fix? (If so, feel free to close the issue as well.)

**Comment by VincentSe** [comment]
Do you mean `upper_bound : exists r, upper r`? Yes, I can do this fix.

**Comment by andrejbauer** [comment]
This was closed by #15
